// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKl_NA05IYAjq-eRl-jo6NrhFZfUOsbE',
    appId: '1:653333796216:web:93cb68a1628dd88672648d',
    messagingSenderId: '653333796216',
    projectId: 'english-learning-app-d0f7e',
    authDomain: 'english-learning-app-d0f7e.firebaseapp.com',
    storageBucket: 'english-learning-app-d0f7e.firebasestorage.app',
    measurementId: 'G-L8RCBKDT2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZyYvBIBdYpD6z4ceYcRiiMyPM06JcSLA',
    appId: '1:653333796216:android:95d4d35556b4a4f372648d',
    messagingSenderId: '653333796216',
    projectId: 'english-learning-app-d0f7e',
    storageBucket: 'english-learning-app-d0f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzGJ9Bn9ZOVeLKDUYAUHe9w0M4sT0gOs',
    appId: '1:653333796216:ios:51de782ba966ae4272648d',
    messagingSenderId: '653333796216',
    projectId: 'english-learning-app-d0f7e',
    storageBucket: 'english-learning-app-d0f7e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZzGJ9Bn9ZOVeLKDUYAUHe9w0M4sT0gOs',
    appId: '1:653333796216:ios:51de782ba966ae4272648d',
    messagingSenderId: '653333796216',
    projectId: 'english-learning-app-d0f7e',
    storageBucket: 'english-learning-app-d0f7e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjKl_NA05IYAjq-eRl-jo6NrhFZfUOsbE',
    appId: '1:653333796216:web:cfc826caa77bc37772648d',
    messagingSenderId: '653333796216',
    projectId: 'english-learning-app-d0f7e',
    authDomain: 'english-learning-app-d0f7e.firebaseapp.com',
    storageBucket: 'english-learning-app-d0f7e.firebasestorage.app',
    measurementId: 'G-1X6M83XGSM',
  );
}
